[package]
name = "wiscoins_project"
version = "1.0.0"
authors = []

[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework" }
MoveStdlib = { local = "../aptos-core/aptos-move/framework/move-stdlib" }

[dev-addresses]
[addresses]

